VMLS - Study Guide Chapter 11 - Matrix Inverses
__Name:__ Joaquin Quintana
* Submit your work in Gradescope as a PDF.
* Identify the question number as you submit.
* One section per page (if a page or less)
* Do not start a new question in the middle of a page.
* Remember to add interpretation, an example, your attempt vs. given solution or other
evidence of your engagement with the material for full credit.


In [1]:
import numpy as np
import itertools
from IPython.display import Latex

Name: Joaquin Quintana

display(Latex(r"\newpage"))

## Triangular matrix. 

In [2]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
    #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
            #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

In [3]:
def back_subst(R,b_tilde):
    n = R.shape[0]
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i] = b_tilde[i]
        for j in range(i+1,n):
            x[i] = x[i] - R[i,j]*x[j]
        x[i] = x[i]/R[i,i]
    return x

def back_solve(R,b):
    n,n = R.shape
    #solving linear equations using QR factorization
    #compute QR factorization of A matix with size n*n
    Q, R = np.linalg.qr(A)
    #compute QTb
    QTransposeb = Q.T@b
    #back substitution 
    x = back_subst(R, QTransposeb)
    return x

In [4]:
R = np.triu(np.random.random((4,4))) #zero anything not in upper triangle
b = np.random.random(4)
x = back_subst(R,b)
np.linalg.norm(R @ x - b)

1.594436429147036e-16

In [5]:
def back_solve(R,b):
    n,n = R.shape
    #solving linear equations using QR factorization
    #compute QR factorization of A matix with size n*n
    Q, R = np.linalg.qr(R)
    #compute QTb
    QTransposeb = Q.T@b
    #back substitution 
    x = back_subst(R, QTransposeb)
    return x

In [6]:
#solving linear equations using QR factorization
A= np.random.rand(3,3)
n = A.shape
b = np.random.rand(n[1])
#compute QR factorization of A matix with size n*n
Q, R = np.linalg.qr(A)
#compute QTb
QTransposeb = Q.T@b
#back substitution 
x = back_subst(R, QTransposeb)
x

array([-0.79638381,  0.23691744,  0.52370483])

In [7]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
    #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
            #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q


Here lets create a lower trinagle matrix with non-zero diagnoal. 

In [8]:
#create a lower trinagle matrix with non-zero diagnoal 
lT = np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)
print("Lower Triagular :\n",lT,"\n \n","Transpose of Lower Triagular :\n",lT.T)

Lower Triagular :
 [[1 0 0]
 [4 5 0]
 [7 8 9]] 
 
 Transpose of Lower Triagular :
 [[1 4 7]
 [0 5 8]
 [0 0 9]]


Now show columns are linerally independent not by proof but by running gram schmidt on the columns. 

In [9]:
R = lT.T
gram_schmidt(R)

Vectors are linearly independent.


[array([0.12309149, 0.49236596, 0.86164044]),
 array([-0.94499299,  0.32328708, -0.04973647]),
 array([-0.30304576, -0.80812204,  0.50507627])]

Now the problem claims if a matrix $R$ is upper triangular with nonzero diagonal then $L = R^T$ is lower triangular with the same diagnoal (shown above) the following formula can be used to find the inverse of the transpose $(L^T)^{-1}  = (L^{-1})^T$.

In [10]:
L = R.T
#compute the inverse of L transposed
R_inverse = np.linalg.inv(L.T)
#matrix multiplication of R and it's inverse should result in I. Some rounding error so drop small elements. 
I = R@R_inverse
I[I < 0.00001] = 0
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Next for the proof I'll replicate it via python. Here we want to show the columns of matrix $L$ of size $n*n$ are linerally independent, this is, $Lx = 0$.   

First let us show all items in the lower triangluar corner and along the non zero diagonal are $L_{i,j} \neq 0.$ 

In [11]:
print("Print True if the value in the array is zero else false: \n\n",L, "\n\n",L == 0)

Print True if the value in the array is zero else false: 

 [[1 0 0]
 [4 5 0]
 [7 8 9]] 

 [[False  True  True]
 [False False  True]
 [False False False]]


Now this implies that the only way $Lx = 0$ is if all the entries of $x$ are zero. For example, in the next cell we run the computation 100000 times with a different x each time. The result is appended as a list and the accumulated list is converted to an array. Finally the result is checked to see if any of the results are zero vectors, which they should not be.

In [12]:
r = []
n,n = L.shape
zero = np.zeros(n)
for i in range(100000):
    x = np.random.rand(n)
    r.append(L@x == zero) #this should never return true
result = np.array(r)
result.any()#are any of the results true

False

In [13]:
r = []
n,n = L.shape
zero = np.zeros(n)
for i in range(100000):
    x = np.random.rand(n)
    r.append(L@zero == zero) #
result = np.array(r)
result.any()#are any of the results true

True

# 11.2 Left and Right Inverse
Left inverse: $XA = I$

Right inverse: $AX = I$

Here I will let $x$ be a nonzero $n$-vector with size greater than 1.

__a)__ Is there a left inverse for $x$

Yes - for any index i with $a_i \neq 0$, the row $n$-vector $x = (\frac{1}{a_i})e^T_i$ satisfies $xa = 1$. $a$ is of size $n*1$ or is a tall matrix with one column. Here is an example showing this for all $i$ for $i = 1,...,n$. 

pg.199

In [14]:
a = np.random.randint(1,20,size = (20,1)) #set range between 1 and n as we want to show the above holds for all i.
n = a.shape
x_i = []
for i in range(n[0]):
    e_i = np.zeros(n)
    #i = 3
    e_i[i] = 1 #change single value to one to create our unit vector e_i
    #compute x using any i in array which does not eqaul 0. This is the inverse of a
    x_i = (1/a[i])*e_i.T 

    #show the xa = 1 for all i
    l = (x_i@a)
    #
    cleanupArray = list(itertools.chain(*l))
    print(np.array(cleanupArray))

[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]


### b
We are looking for a matrix $A$ which satifies the following matrix function 

__Right inverse:__ $AX = I$

From pg 201 of VMLS we know only square and wide matricies can be right-invertable. Since our matrix is tall we know there is no right inverse. 

# 11.3

Show that any random nonzero matrix $A$ is insufficent to conclude $X=Y$. Both sides of the equality $AX=AY$ are right inverses and we would expect the result of $AX = AY = I$

In [15]:
#a
A = np.array([1,0,1,0,1,0,1,0,1,0]) 
X = np.array([0,1,0,1,0,1,0,1,0,1]) 
Y  = np.array([0,0,0,0,0,0,0,0,0,0])
A@X==A@Y# we get the same result but X !=Y
#eval AX and eval AY show this random matrix A does not work here.  
print("X = \n",X,"\n\nY = \n",Y,"\n\nDoes X == Y : \n",all(X==Y),"\n\nAX = \n",A@X,"\n\n","AY = \n",A@Y,"\n\n","A@X == A@Y :\n",A@X == A@Y)

X = 
 [0 1 0 1 0 1 0 1 0 1] 

Y = 
 [0 0 0 0 0 0 0 0 0 0] 

Does X == Y : 
 False 

AX = 
 0 

 AY = 
 0 

 A@X == A@Y :
 True


### b

In [16]:
#b 
A = np.random.randint(1,20,size = (2,2)) 
X = np.random.randint(1,20,size = (2,2)) 
Y = X #let Y == X
#find the inverse of A and call it B
B = np.linalg.inv(A)

Let's multiply both side of the the funtion $AX = AY$ by B. The gives $B(AX) = B(AY)$ and by reassociation we get $BA(X) = BA(Y)$. Now lets show that $BA=I$.  

In [17]:
BA = B@A
BA[BA < 0.00001] = 0
print("BA = \n", BA)

BA = 
 [[1. 0.]
 [0. 1.]]


From this we can conclude that $X==Y$ and here is an example to show this is true. 

In [18]:
(BA@X == BA@Y) == (A@X == A@Y)

array([[ True,  True],
       [ True,  True]])

### C

Here a is not invertable as more than one of the columns is zero. Therefore the columns are linearlly dependent, but we can show that there are matricies $X$ and $Y$ with $X \neq Y$ and $AX = AY$

In [19]:
#c credit to Trent Resh and Cooper Ide for posting hints for parts C on piazza 
a  = np.array([[1,0,0],[1,0,0],[1,0,0]])
#x and y share the same first row, but differ in all other inputs
x = np.array([[2,2,2],[5,4,2],[3,2,1]])
y = np.array([[2,2,2],[4,5,6],[4,5,6]])
a@x==a@y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 11.4

Lets create a n*n matrix and run gram-schmidt on it to get a set of orthonormalized vectors. Then we can use this for the problem. 

In [20]:
A = np.random.randint(1,20,size = (10,10))
Q = gram_schmidt(A)
q = np.array(Q)

Vectors are linearly independent.


Since $U$ is sqaure we can show that $U^TU = I$ and at the same time show the inverse of $U$ is simply $U^T$

In [21]:
qTq = q.T@q
qTq[qTq < 0.00001] = 0
qTq

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

We see that $q^Tq = I$ and therefore can conclude that $q^T$ is the inverse of $q$. We can also show that $qq^T = I$

In [22]:
qqT = q@q.T
qqT[qqT < 0.00001] = 0
qqT

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Finally since the transpose of $q$ is the inverse of $q$ we can conclude the matrix $q^T$ is orthogonal. 

# 11.15

Starting with things that do not work. In the next cell make $d_1 = 0$.

In [23]:
b = np.random.rand(5) #b_i greater than eqaul to zero
n = b.shape
d = np.random.rand(n[0]-1)
oneMinusd = 1-d
##
# set one element to 1
#let d_k = 1 for some k which means 1-d_k = 1-1 = 0. Simply make one of
oneMinusd[1] = 1 

#create rows 1 to n 
z = np.zeros((n[0]-1,n[0]))
for i in range(n[0]-1):
    #print(i,i)
    z[i,i] = 1-oneMinusd[i]
    
#create Population dynamics matrix shown in problem 
A = np.vstack((b,z))
A

array([[0.89137207, 0.37033185, 0.16621556, 0.42551929, 0.69613119],
       [0.73791689, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.24561207, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.31926024, 0.        ]])

Since $d_1 = 0$ the $(k+1)th$ row of $A$ is zero, which in this case is row 2, so the rows are linerally dependent and $A$ is not invertable. 

We can show this using gram schmidt. 

In [24]:
gram_schmidt(A)

Vectors are linearly dependent.
GS algorithm terminates at iteration  3


[array([0.69925349, 0.29051375, 0.1303909 , 0.33380657, 0.54609313]),
 array([ 0.7148738 , -0.28416589, -0.1275418 , -0.32651274, -0.53416075])]

Now let $b_n = 0$ and again show that the columns are linerally dependent do to the last column being all zeros. 

In [25]:
b = np.random.rand(5) #b_i greater than eqaul to zero
n = b.shape
d = np.random.rand(n[0]-1)
oneMinusd = 1-d

#create rows 1 to n 
z = np.zeros((n[0]-1,n[0]))
for i in range(n[0]-1):
    #print(i,i)
    z[i,i] = 1-oneMinusd[i]
    
#create Population dynamics matrix shown in problem 
A = np.vstack((b,z))
#
A[0,4] = 0
print("A : \n", A)

A : 
 [[0.61781597 0.91887567 0.36161998 0.83210086 0.        ]
 [0.72174245 0.         0.         0.         0.        ]
 [0.         0.77467359 0.         0.         0.        ]
 [0.         0.         0.48168227 0.         0.        ]
 [0.         0.         0.         0.93350766 0.        ]]


In [26]:
gram_schmidt(A.T)

Vectors are linearly dependent.
GS algorithm terminates at iteration  5


[array([0.65029343, 0.75968313, 0.        , 0.        , 0.        ]),
 array([ 0.50854249, -0.4353155 ,  0.7428896 ,  0.        ,  0.        ]),
 array([ 0.22016781, -0.188465  , -0.26115108,  0.92076446,  0.        ]),
 array([ 0.21840428, -0.18695541, -0.25905928, -0.16396566,  0.90738679])]

### What will work

If $d<1$ for $i = 1, ..., n$ and $b_n > 0$ we can show that $Ax = 0$ implies $x = 0$. For example lets start with showing such a matrix $A$ has linerally independent columns and rows. 

In [27]:
b = np.random.rand(5) #b_i greater than eqaul to zero
n = b.shape
d = np.random.rand(n[0]-1)
oneMinusd = 1-d

#create rows 1 to n 
z = np.zeros((n[0]-1,n[0]))
for i in range(n[0]-1):
    #print(i,i)
    z[i,i] = 1-oneMinusd[i]
    
#create Population dynamics matrix shown in problem 
A = np.vstack((b,z))
gram_schmidt(A)
gram_schmidt(A.T)

Vectors are linearly independent.
Vectors are linearly independent.


[array([0.89905414, 0.43783747, 0.        , 0.        , 0.        ]),
 array([ 0.43600505, -0.89529145,  0.09139378,  0.        ,  0.        ]),
 array([ 0.0020127 , -0.00413288, -0.05008744,  0.99873426,  0.        ]),
 array([ 3.01802438e-04, -6.19720218e-04, -7.51055046e-03, -3.79833683e-04,
         9.99971486e-01]),
 array([ 0.03996383, -0.08206161, -0.99452603, -0.05029651, -0.00755167])]

Now we know A is square with linearlly independent columns and rows so it is invertable. We know that $Ax = 0$ and the row wise inner product of A and the $n$-vecotor x can only eqaul zero if all $x_i$ for $i = 1, ...,n $ equals zero. For example, in the first cell we run the computation 1000 times with a different x each time. The result is appended as a list and the accumulated list is converted to an array. Finally the result is checked to see if any of the results are zero vectors, which they should not be.

In [28]:
r = []
for i in range(1000):
    x = np.random.rand(n[0])
    zero = np.zeros(n[0])
    r.append(A@x == zero) #this should never return true
result = np.array(r)
result.any()#are any of the results true

False

This next cell show that $Ax = 0$ if x if all $x_i = 0$.

In [29]:
#show that it does return a zero vector when x is all zeros
r = []
for i in range(1000):
    #x = np.random.rand(n[0])
    zero = np.zeros(n[0])
    r.append(A@zero == zero) #
result = np.array(r)
result.all()#are all of the results true

True

# 11.16

Let's start by creating a running sum matrix of size $n*n$, call it $S$ and an n-vector x. 

In [30]:
#create running sum matrix 
n = 10
S = np.tril(np.ones((n,n)))
S

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
x = 10*np.random.rand(n)
x

array([2.96553141, 5.00616719, 9.58259091, 5.81349045, 4.11707133,
       5.02902361, 4.27436201, 0.79226821, 1.19982661, 7.67760946])

The running sum matrix can be used to compute the $i$th entry of an $n$-vector. This is, $Sx$ can be used to compute the sum of the first $i$ entries of $x$. 

$Sx = \begin{bmatrix} x_1 \\ x_1+x_2 \\ x_1+x_2+x_3 \\...\\ x_1+...+x_n \end{bmatrix}$

Here is a simple example of computing the running sum of vector $x$ in python. 

In [32]:
S@x

array([ 2.96553141,  7.9716986 , 17.55428952, 23.36777996, 27.4848513 ,
       32.51387491, 36.78823692, 37.58050513, 38.78033174, 46.4579412 ])

Now lets compute the inverse of such a running matrix and look at it. 

In [33]:
#compute the left inverse
inv = np.linalg.inv(S)
inv

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.]])

Show that this is indeed the left inverse of such a running matrix. We can do this by showing $S^{-1}S = I$

In [34]:
inv@S

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Show that the muliplication of the inverse of $x$ and $x$ returns the difference matrix of $x$.

In [35]:
inv@x

array([ 2.96553141,  2.04063578,  4.57642372, -3.76910046, -1.69641911,
        0.91195228, -0.75466161, -3.48209379,  0.4075584 ,  6.47778284])

Compute differnce matrix of x using numpy. Note numpy only returns results where the differnce is computed and does not include the first element as it is $x_1$ and computes no differnce. When using the matrix multiplication the first element is retuned in the result. 

In [36]:
np.diff(x)

array([ 2.04063578,  4.57642372, -3.76910046, -1.69641911,  0.91195228,
       -0.75466161, -3.48209379,  0.4075584 ,  6.47778284])

Here the running sum returns the sum of the first i entries. So the inverse being a matrix like the difference matrix makes sence as it is esentaially the reverse process of the running sum matrix computation. 