In [1]:
import numpy as np

#quiz 11

In [3]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
    #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
            #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

In [6]:
#3?
a = np.array([[1,2],[0,-2]])
b = np.array([[1,1],[0,-1/2]])
a@b
b@a

array([[1., 0.],
       [0., 1.]])

In [9]:
#4 
A = np.array([[-1,4],[1,-1]])
A


array([[-1,  4],
       [ 1, -1]])

In [12]:
#3
A = np.array([[-2,6],[-2,5]])
A
inv = np.linalg.inv(A)

inv

array([[ 2.5, -3. ],
       [ 1. , -1. ]])

In [13]:
def back_subst(R,b_tilde):
    n = R.shape[0]
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i] = b_tilde[i]
        for j in range(i+1,n):
            x[i] = x[i] - R[i,j]*x[j]
        x[i] = x[i]/R[i,i]
    return x

def back_solve(R,b):
    n,n = R.shape
    #solving linear equations using QR factorization
    #compute QR factorization of A matix with size n*n
    Q, R = np.linalg.qr(A)
    #compute QTb
    QTransposeb = Q.T@b
    #back substitution 
    x = back_subst(R, QTransposeb)
    return x

In [63]:
a = np.array([[3,2],[4,6]])
# = np.array([4,6])
b = np.array([2,4])

In [64]:
x = np.linalg.solve(a, b)
x

array([0.4, 0.4])

In [38]:
x=4/10
y = 6/15
3*x+2*y

2.0

In [39]:
4*x+6*y

4.0

In [72]:
A = np.array([[-1,4],[1,-1]])
I = np.identity(2)
np.linalg.inv(A)

array([[0.33333333, 1.33333333],
       [0.33333333, 0.33333333]])

In [40]:
#ax=b a coefficents
#b output
x = np.linalg.solve(a, b)
x

array([-0.4,  0.8])

In [54]:
a = np.array([[2,3,1],[1,4,1],[1,3,1]])
# = np.array([4,6])
b = np.array([-6,-12,-9])

In [55]:
#b output
x = np.linalg.solve(a, b)
x

array([ 3., -3., -3.])

In [56]:
X = np.linalg.inv(a).dot(b)
X

array([ 3., -3., -3.])

In [57]:
2*X[0]+3*X[1]+X[2]

-6.000000000000002

In [58]:
X[0]+4*X[1]+X[2]

-12.000000000000004

In [59]:
X[0]+3*X[1]+X[2]

-9.000000000000004

In [73]:
A = np.array([[-4,2],[5,2]])
A

array([[-4,  2],
       [ 5,  2]])

In [75]:
(-1/18)*A

array([[ 0.22222222, -0.11111111],
       [-0.27777778, -0.11111111]])

In [82]:
4/18

0.2222222222222222

In [83]:
A = np.array([[-3,-3],[4,-2]])
A

array([[-3, -3],
       [ 4, -2]])

In [84]:
np.linalg.inv(A)

array([[-0.11111111,  0.16666667],
       [-0.22222222, -0.16666667]])

In [87]:
A = np.array([[1,2],[0,-2]])
B = np.array([[1,1],[0,-1/2]])
A@B

array([[1., 0.],
       [0., 1.]])

In [88]:
a = np.array([[4,2],[5,3]])
# = np.array([4,6])
b = np.array([5,4])

In [91]:
x = np.linalg.solve(a,b)

In [93]:
4*x[0]+2*x[1]

4.999999999999998

In [94]:
x

array([ 3.5, -4.5])

In [95]:
5*x[0]+3*x[1]

3.9999999999999982

In [96]:
a = np.array([[4,2,1],[2,5,2],[1,2,1]])
# = np.array([4,6])
b = np.array([-15,-13,-6])

In [97]:
x = np.linalg.solve(a,b)

In [98]:
4*x[0]+2*x[1]+x[2]

-15.0

In [99]:
2*x[0]+5*x[1]+2*x[2]

-13.0

In [100]:
x[0]+2*x[1]+x[2]

-6.0

In [101]:
x

array([-3., -1., -1.])

In [7]:
I = np.identity(2)
I[0]

array([1., 0.])

In [9]:
gram_schmidt(I)

Vectors are linearly independent.


[array([1., 0.]), array([0., 1.])]

In [10]:
# 
# Discrete Fourier transform (Python)
# by Project Nayuki, 2017. Public domain.
# https://www.nayuki.io/page/how-to-implement-the-discrete-fourier-transform
# 


# 
# Computes the discrete Fourier transform (DFT) of the given complex vector.
# 'input' is a sequence of numbers (integer, float, or complex).
# Returns a list of complex numbers as output, having the same length.
# 
import cmath
def compute_dft_complex(input):
    n = len(input)
    output = []
    for k in range(n):  # For each output element
        s = complex(0)
        for t in range(n):  # For each input element
            angle = 2j * cmath.pi * t * k / n
            s += input[t] * cmath.exp(-angle)
        output.append(s)
    return output
    

# 
# (Alternate implementation using only real numbers.)
# Computes the discrete Fourier transform (DFT) of the given complex vector.
# 'inreal' and 'inimag' are each a sequence of n floating-point numbers.
# Returns a tuple of two lists of floats - outreal and outimag, each of length n.
# 
import math
def compute_dft_real_pair(inreal, inimag):
    assert len(inreal) == len(inimag)
    n = len(inreal)
    outreal = []
    outimag = []
    for k in range(n):  # For each output element
        sumreal = 0.0
        sumimag = 0.0
        for t in range(n):  # For each input element
            angle = 2 * math.pi * t * k / n
            sumreal +=  inreal[t] * math.cos(angle) + inimag[t] * math.sin(angle)
            sumimag += -inreal[t] * math.sin(angle) + inimag[t] * math.cos(angle)
        outreal.append(sumreal)
        outimag.append(sumimag)
    return (outreal, outimag)