In [1]:
import numpy as np

The 4 properties of matrix multiplication.

* __The inner product and matrix-vector products__ pg.179

* __Inner product representation__ 

* __A block matrix multiplication__

* __A column interpretation of matrix-matrix product__

* Multiple sets of linear equations (skip row interpretation if you wish)? Not sure what to do for this?

* __Gram Matrix__

* __Outer Product representation__

# inner product and matrix-vector products

Let $y$ be an $m$-vector, $x$ be an $n$-vector and $A$ an $m*n$ matrix. We will show that $y^T(Ax) = (y^TA)x = (A^Ty)^Tx$. In python...

In [2]:
#creat A
A = np.random.rand(6,3)
m,n = A.shape
#create y 
y = np.random.rand(m)
#create x
x = np.random.rand(n)

compute $y^T(Ax)$

In [3]:
y.T@(A@x)

2.0148158833801686

compute $(y^TA)x$

In [4]:
(y.T@A)@x

2.014815883380169

compute $(A^Ty)^Tx$

In [5]:
(A.T@y).T@x

2.014815883380169

Show the equivalence between these outputs. This, $y^T(Ax) == (y^TA)x == (A^Ty)^Tx$

In [6]:
y.T@(A@x) == (y.T@A)@x == (A.T@y).T@x

False

# Block Matrix

Here let A and B block matricies of size $4*4$. Each block matrix is compose of four matricies of the same size denoted with lowercase letter. Following from formula 10.1 we can let C = AB to get. 

$C = AC =  \begin{bmatrix} a & b\\ c & d \end{bmatrix} \begin{bmatrix} e & f\\ g & h \end{bmatrix} = \begin{bmatrix} ae + bg & af + bh \\ ce +dg & cf +dh \end{bmatrix} $

In [7]:
#create sub matricies pg.180
a = np.random.rand(2,2)
b = np.random.rand(2,2)
c = np.random.rand(2,2)
d = np.random.rand(2,2)
e = np.random.rand(2,2)
f = np.random.rand(2,2)
g = np.random.rand(2,2)
h = np.random.rand(2,2)
#create block matricies A and B
A= np.block([[a,b],[c,d]])
B= np.block([[e,f],[g,h]])

## Show C is equivalent to A@B 
(note if checking equivalence some rounding error will exist between the two results).

In [8]:
A@B

array([[2.26682808, 1.98137673, 2.51299528, 1.60507833],
       [1.00038896, 0.96747159, 1.65543286, 1.19082491],
       [1.26866282, 1.03779527, 1.31337688, 0.77303084],
       [0.58694951, 0.67525295, 1.24260099, 0.86847231]])

In [9]:
C = np.block([[a@e + b@g, a@f + b@h],[c@e + d@g, c@f + d@h]])
C

array([[2.26682808, 1.98137673, 2.51299528, 1.60507833],
       [1.00038896, 0.96747159, 1.65543286, 1.19082491],
       [1.26866282, 1.03779527, 1.31337688, 0.77303084],
       [0.58694951, 0.67525295, 1.24260099, 0.86847231]])

# Outer Product representation 
Let A be of size $m*p$ and express this matrix in terms of it columns we get, $A = [a_1,...,a_p]$. Let B be a matrix of size $p*n$ and express it this matrix B as the rows transposed which is, $B = \begin{bmatrix} b^T_1 \\.\\.\\.\\ b^T_p\end{bmatrix}$. In python this looks like...

In [10]:
#pg.177
A = np.array([[-1.5,3,2],[1,-1,0]])
B = np.array([[-1,-1],[0,-2],[1,0]])

In [11]:
#This is correctly computing the Outer product representation. 
m,p = A.shape
out = []
for i in range(p):
    #take the outer product of the columns of a and the rows of b. Make sure b_i has the correct shape here. 
    out.append(np.outer(A[:,i],B[i,:].reshape(2,1)))
          
sum(out)

array([[ 3.5, -4.5],
       [-1. ,  1. ]])

In [12]:
#pg. 191 Inner product representation. matrix multiplication A row wise and columns B

AB1=A[0,:]@B[:,0]
AB2=A[0,:]@B[:,1]
AB3 = A[1,:]@B[:,0]
AB4 = A[1,:]@B[:,1]

#place it all back together 
np.array([[AB1,AB2],[AB3,AB4]])

array([[ 3.5, -4.5],
       [-1. ,  1. ]])

# column representation matrix matrix product pg 190
A has size n*p and B p*n

$AB = A[b_1,b_2,...,b_n] = [Ab_1,Ab_2,...,Ab_n]$

In python ...

In [13]:
#pg. 181 Inner product representation 
AB1=A@B[:,0]
AB2=A@B[:,1]
#place it all back together 
np.vstack((AB1,AB2)).T

array([[ 3.5, -4.5],
       [-1. ,  1. ]])

# Gram Matrix

The gram matrix is created by taking the inner product of the matrix transposed and the same matrix untransposed. This is, $G = A^TA$ transpose ^T. Here is an example in python.

In [14]:
#imples the matrix is transposed first
G = A.T@A
G

array([[ 3.25, -5.5 , -3.  ],
       [-5.5 , 10.  ,  6.  ],
       [-3.  ,  6.  ,  4.  ]])

# block matrix multiplication


In [15]:
A = np.ones((2, 3), int)
B = 9 * A
BlockA = np.block([[A, B],[B,A]]) 
print("BlockA shape: ",BlockA.shape)

BlockA shape:  (4, 6)


In [16]:
D = np.ones((3, 2), int)
Dstack = np.vstack([D,D])
BlockB = np.block([[D,-2*B.T],[D*5,B.T]])
print("BlockB shape: ",BlockB.shape)

BlockB shape:  (6, 4)


In [17]:
C = BlockA@BlockB
C

array([[ 138,  138,  189,  189],
       [ 138,  138,  189,  189],
       [  42,   42, -459, -459],
       [  42,   42, -459, -459]])

# Quiz

In [18]:
31 
p = np.array([[1],[1],[1]])
po = np.array([[1],[1]])
p@po.T

array([[1, 1],
       [1, 1],
       [1, 1]])

In [19]:
B = np.random.rand(10,5)
BB_t = B@B.T
BB_t.shape

(10, 10)

In [20]:
B.T.shape

(5, 10)

In [21]:
#3
a = np.array([8,6,6,6,7,4,9,7,8]).reshape(3, 3, order='F') 
b = np.array([5,6,2,2,1,4,5,1,7]).reshape(3, 3, order='F') 
a+b
4*b
a@b

array([[ 94,  58, 109],
       [ 86,  47,  86],
       [ 70,  48,  90]])

In [22]:
#3 quiz 2
aS = "377643489"



In [23]:
#4 
a = np.array([0,2,0,3,0,2,0,1,2]).reshape(3, 3, order='F') 
b = np.array([0,3,4,3,2,0,4,1,0]).reshape(3, 3, order='F') 
a@b - b@a

array([[ 3, -2, -8],
       [ 0, -5,  4],
       [14, -8,  2]])

In [24]:
# 5 
a = np.array([2,5,5,0]).reshape(2, 2, order='F') 
b = np.array([3,7,7,5,4,2]).reshape(2, 3, order='F') 
a.T@b

array([[41, 39, 18],
       [15, 35, 20]])

In [25]:
#6 
a = np.array([2,2,3,3,1,5,1,2,3]).reshape(3, 3, order='F') 
b = np.array([4,1,5,4,3,4,4,3,4]).reshape(3, 3, order='F')
print("c1 =\n ", a@b)
print("c2 = \n", b@a)

c1 =
  [[16 21 21]
 [19 19 19]
 [32 39 39]]
c2 = 
 [[28 36 24]
 [17 21 16]
 [30 39 25]]


In [26]:
# 7 
a = np.array([3,4,2,1,1,3,3,1,1]).reshape(3, 3, order='F') 
b = np.array([5,1,4,2,5,1,5,5,3]).reshape(3, 3, order='F')
print("c1 =\n ", a@b)
print("c2 = \n", b@a)
a@b - b@a

c1 =
  [[28 14 29]
 [25 14 28]
 [17 20 28]]
c2 = 
 [[33 22 22]
 [33 21 13]
 [22 14 16]]


array([[-5, -8,  7],
       [-8, -7, 15],
       [-5,  6, 12]])

In [27]:
#8 
a = np.array([1,2,3,4])
b = np.array([7,8,3,9])
print("AB = ", a@b)
print("BA = ", np.outer(b,a))

AB =  68
BA =  [[ 7 14 21 28]
 [ 8 16 24 32]
 [ 3  6  9 12]
 [ 9 18 27 36]]


In [28]:
# 9 ?
a = np.array([7,0,7,3,4,5]).reshape(3,2, order='F') 
b = np.array([6,6,0,0,5,6,2,6,6]).reshape(3, 3, order='F')
a.T@b

array([[42, 42, 56],
       [42, 50, 60]])

In [29]:
a = np.array([-1,-2,1,1]).reshape(2,2, order='F') 
b = np.array([-9,-6,3,-3]).reshape(2,2, order='F')
print(a@b)
print(b@a)

[[ 3 -6]
 [12 -9]]
[[ 3 -6]
 [12 -9]]


In [30]:
#11 
a = np.array([1,3,-5,-3,3,-1,2,2,2]).reshape(3, 3, order='F') 
x = np.array([2,2,-2]).T
a@x

array([ -8,   8, -16])

In [31]:
#12
a = np.array([4,3,5,-5,2,1,2,1,5]).reshape(3, 3, order='F') 
x = np.array([2,1,-3]).T
a@x

array([-3,  5, -4])

# 10.39


In [32]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
    #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
            #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q


### This is the QR factorization of A as it expresses martix A as the product of two matricies Q and R. 

In [33]:
A= np.random.rand(3,3)
A

array([[0.71170705, 0.91457585, 0.14817673],
       [0.21234468, 0.39563129, 0.69424138],
       [0.69614292, 0.23953124, 0.13596049]])

In [34]:
def QR_factorization(A):
    #transpose A to use columns in gram schmidt
    Q_transpose = np.array(gram_schmidt(A.T))
    #create matrix R by multiplying Q by A
    R = Q_transpose @ A
    #transpose Q and return result
    Q = Q_transpose.T
    return Q, R

Q, R = QR_factorization(A)
Q

Vectors are linearly independent.


array([[ 0.69915382,  0.5727913 , -0.42789492],
       [ 0.20859931,  0.40901994,  0.88836311],
       [ 0.68386422, -0.71036105,  0.16648398]])

In [35]:
Q, R = np.linalg.qr(A)
Q

array([[-0.69915382, -0.5727913 , -0.42789492],
       [-0.20859931, -0.40901994,  0.88836311],
       [-0.68386422,  0.71036105,  0.16648398]])

Show that $G = A^TA = (QR)^T(RQ) = R^TQ^TQR = R^T(Q^TQ) = R^TR$

In [36]:
G = A.T@A
G

array([[1.03623216, 0.90166826, 0.34752482],
       [0.90166826, 1.05034833, 0.44274926],
       [0.34752482, 0.44274926, 0.52241269]])

In [37]:
qrTrq = ( (Q@R).T) @ (Q@R) 
qrTrq

array([[1.03623216, 0.90166826, 0.34752482],
       [0.90166826, 1.05034833, 0.44274926],
       [0.34752482, 0.44274926, 0.52241269]])

In [38]:
rTqTqr = R.T @ (Q.T@Q) @ R

In [39]:
R.T@R

array([[1.03623216, 0.90166826, 0.34752482],
       [0.90166826, 1.05034833, 0.44274926],
       [0.34752482, 0.44274926, 0.52241269]])

In [40]:
print("Are all the intermediates above equivalent : ",G.all() == qrTrq.all() == rTqTqr.all() == (R.T@R).all())

Are all the intermediates above equivalent :  True


I agree. I think I'm making a mistake here. This assumes you run the algorithm starting at column 1 and then d is a subset and therefore all the sub matrix results for A are also computed. 




However if you  compute the QR factorization of A and then a subset A, say starting at column 2, the two sets of linear equations are different and the results of the sub matrix  

# 10.40 

The claim of this problem is that when you compute the QR factorization $A = QR$ you are also computing the QR factorization for all submatricies of A. Here A is a $n*k$ matrix which we run gram-schmidt on the columns of to obtain matricies Q and R. Now with this information the problem does make sense since we are using the gram-schmidt algorithm to compute $Q$ and $R$ given $A$. Since the columns of A are linerally independent (known as the gram-schmidt does not terminate) we can say any submatrix with column index less than k is also linerally independent. 

__Notes__

Where $i$ is an index between 1 and k. 

$A_i = A_{1:n,1:i}$

$Q_i = Q_{1:n,1:i}$

$R_i = R_{1:i,1:i}$

In [41]:
A= np.random.rand(5,5)
print("Matrix A: \n", A,"\n \n","shape of A: ", A.shape)

Matrix A: 
 [[0.42144436 0.34395741 0.83734914 0.57031749 0.35982958]
 [0.99207483 0.58466526 0.08084211 0.94836541 0.9561474 ]
 [0.90321986 0.19715076 0.45104273 0.08770035 0.29472147]
 [0.93850787 0.92971231 0.48569581 0.65749173 0.16729522]
 [0.02549593 0.76973296 0.45155574 0.91638192 0.6238269 ]] 
 
 shape of A:  (5, 5)


In [42]:
A= np.random.rand(5,5)
print("Matrix A: \n", A,"\n \n","shape of A: ", A.shape)
#compute Q and R
Q, R = np.linalg.qr(A)
print("Q : \n", Q)
print("R : \n", R)

Matrix A: 
 [[0.18528456 0.89669197 0.9175411  0.21803961 0.31923499]
 [0.29269177 0.5527958  0.78669106 0.284544   0.00714607]
 [0.18366434 0.55053761 0.93858668 0.093445   0.24038085]
 [0.86961895 0.99333042 0.58830807 0.57294491 0.91846692]
 [0.44341888 0.91210594 0.28469571 0.92946866 0.58445302]] 
 
 shape of A:  (5, 5)
Q : 
 [[-0.17613517  0.77291835  0.03893169 -0.56018542 -0.23717134]
 [-0.27823859  0.13105756 -0.47190438  0.5105625  -0.64964559]
 [-0.17459496  0.33923733 -0.57036382  0.18553937  0.7033455 ]
 [-0.82667699 -0.42970432 -0.06940022 -0.35440362  0.03925604]
 [-0.42152277  0.2927343   0.66757719  0.51525862  0.15960714]]
R : 
 [[-1.05194527 -1.61350603 -1.15071804 -0.99932317 -1.10582184]
 [ 0.          0.79244697  0.96123148  0.26340893  0.10564553]
 [ 0.          0.         -0.72162976  0.40164301  0.19837724]
 [ 0.          0.          0.          0.3163356  -0.1549457 ]
 [ 0.          0.          0.          0.          0.21805323]]


Here we can take a sub set of the columns and run QR factorization on them and get the same result as when QR factorization  is run on the whole matrix A. This seems to only be true when you start with column 1 though.

In [43]:
#copute the submatrix of A using only columns and 
#for some reason starting at index other than 1 results in a different input. 
subA = A[:,0:len(A)-1]
subA

array([[0.18528456, 0.89669197, 0.9175411 , 0.21803961],
       [0.29269177, 0.5527958 , 0.78669106, 0.284544  ],
       [0.18366434, 0.55053761, 0.93858668, 0.093445  ],
       [0.86961895, 0.99333042, 0.58830807, 0.57294491],
       [0.44341888, 0.91210594, 0.28469571, 0.92946866]])

In [44]:
#compute Q and R
Qsub, Rsub = np.linalg.qr(subA)
Qsub

array([[-0.17613517,  0.77291835,  0.03893169, -0.56018542],
       [-0.27823859,  0.13105756, -0.47190438,  0.5105625 ],
       [-0.17459496,  0.33923733, -0.57036382,  0.18553937],
       [-0.82667699, -0.42970432, -0.06940022, -0.35440362],
       [-0.42152277,  0.2927343 ,  0.66757719,  0.51525862]])

In [45]:
Rsub

array([[-1.05194527, -1.61350603, -1.15071804, -0.99932317],
       [ 0.        ,  0.79244697,  0.96123148,  0.26340893],
       [ 0.        ,  0.        , -0.72162976,  0.40164301],
       [ 0.        ,  0.        ,  0.        ,  0.3163356 ]])

Now lets say you start at colunm 2 (assuming index starts at 1) and end at n, 
Notice this does not reproduce the same result as the example above as we did not start at column1. We would expect the output of the QR factorization here to be equivalent to the last 4 columns of Q and R, but the set of liner equations used here does not include a1. 

In [46]:
subA = A[:,1:6]
subA

array([[0.89669197, 0.9175411 , 0.21803961, 0.31923499],
       [0.5527958 , 0.78669106, 0.284544  , 0.00714607],
       [0.55053761, 0.93858668, 0.093445  , 0.24038085],
       [0.99333042, 0.58830807, 0.57294491, 0.91846692],
       [0.91210594, 0.28469571, 0.92946866, 0.58445302]])

In [47]:
#compute Q and R
Qsub, Rsub = np.linalg.qr(subA)
Qsub

array([[-0.49882668, -0.23735792,  0.57017133,  0.58376009],
       [-0.30751842, -0.42110171, -0.51424871,  0.25262145],
       [-0.30626219, -0.61219576, -0.18635811, -0.4792452 ],
       [-0.55258632,  0.26924978,  0.34191189, -0.57473326],
       [-0.50740142,  0.56484996, -0.50874338,  0.18818152]])

# 10.43
__Information needed:__ See pg. 182 of VMLS. 

Following from what is provided in problem 10.43. 

Lets assumse we are taking the inner product of the rows of $A$ and the columns of $B$. Then the complexity is ~ $2mnp$ flops. Most of the time we let A be of size $m*p$ and B be of size $p*n$. However here $A$ is the same size as $B$ so we know $m=p$ and $p=n$. This tells us all the terms are equivalent to $n$. Finally, since we know $m = p = n$ we have $2*n*n*n$ and by convention we can drop the constant to get the complexity of $n^3$. 

We are told it takes ~ 0.2 seconds to compute the product of two matricies each of size 1500*1500. This problem has a nice set to solve using a ratio. This is, we have 3 knowns related to one another and one unknown related to the other 3. 

let x1 = 0.2 sec, n1 = 1500 and x2 = t, n2 = 3000

$\frac{x1}{n1} = \frac{x2}{n2}$

Solve for the unkown $x_2$

$x_2 = \frac{x_1n_2}{n1} =  1.6$ seconds

In practice this values will vary but is a good back of the envolpe approximation. 

In [48]:
def convertQuizMatrix(String):
    l = []
    for i in String: 
        l.append(int(i))
    return np.array(l)

In [49]:
#3 Quiz 2
s = "377643489"
s1 = "666547198"
A = convertQuizMatrix(s).reshape(3, 3, order='F') 
B = convertQuizMatrix(s1).reshape(3, 3, order='F') 
A+B
5*B
#A@B

array([[30, 25,  5],
       [30, 20, 45],
       [30, 35, 40]])

In [50]:
#4 Quiz 2
a = "312031033"
b = "221133114"
A = convertQuizMatrix(a).reshape(3, 3, order='F') 
B = convertQuizMatrix(b).reshape(3, 3, order='F') 
A@B-B@A

array([[-3, -1, -3],
       [ 0,  9,  4],
       [-5,  1, -6]])

In [51]:
#5 Quiz 2
a = "225456375"
b = "103744"
A = convertQuizMatrix(a).reshape(3, 3, order='F') 
B = convertQuizMatrix(b).reshape(3, 2, order='F') 
A.T@B

array([[17, 42],
       [22, 72],
       [18, 69]])

In [52]:
#6 Quiz attempt 2
a = "321525154"
b = "213514154"
A = convertQuizMatrix(a).reshape(3, 3, order='F') 
B = convertQuizMatrix(b).reshape(3, 3, order='F') 
print("c1 = ", A@B,"\n")
print("c2 = ", B@A,"\n")

c1 =  [[14 24 32]
 [21 32 32]
 [19 26 42]] 

c2 =  [[17 25 31]
 [10 32 26]
 [21 43 39]] 



In [53]:
#7 Quiz attempt 
a = "122242213"
b = "215354353"
A = convertQuizMatrix(a).reshape(3, 3, order='F') 
B = convertQuizMatrix(b).reshape(3, 3, order='F') 
print("AB = ", A@B,"\n")
print("BA = ", B@A,"\n")
print("AB-BA = ", A@B-B@A,"\n")

AB =  [[14 21 19]
 [13 30 29]
 [21 28 25]] 

BA =  [[14 22 16]
 [21 32 22]
 [19 32 23]] 

AB-BA =  [[ 0 -1  3]
 [-8 -2  7]
 [ 2 -4  2]] 



In [65]:
#8 Quiz attempt 
a = "1234"
b = "1652"
A = convertQuizMatrix(a).reshape(1, 4, order='F') 
B = convertQuizMatrix(b).reshape(4, 1, order='F') 
print("AB = ", A@B)
print("BA = \n", np.outer(B,A))

AB =  [[36]]
BA = 
 [[ 1  2  3  4]
 [ 6 12 18 24]
 [ 5 10 15 20]
 [ 2  4  6  8]]


In [66]:
#9 Quiz attempt 
a = "005737630"
b = "757744"
A = convertQuizMatrix(a).reshape(3, 3, order='F') 
B = convertQuizMatrix(b).reshape(3, 2, order='F') 
print("A^TB = \n", A.T@B)

A^TB = 
 [[ 35  20]
 [113  89]
 [ 57  54]]


In [97]:
#10 Quiz attempt 

A = np.array([-3,1,1,-4]).reshape(2, 2, order='F') 
B = np.array([6,-3,-3,9]).reshape(2, 2, order='F') 

A@B 

array([[-21,  18],
       [ 18, -39]])

For #10 on Quiz 10 use the following equation to compute k. This is use these to find values which allow for AB to commute to BA


$A  = \begin{bmatrix} a & b\\ c & d \end{bmatrix}$

$B = \begin{bmatrix} x & y\\ \frac{cy}{b} & x + \frac{(d-a)y}{b} \end{bmatrix}$

In [98]:
A

array([[-3,  1],
       [ 1, -4]])

In [99]:
B

array([[ 6, -3],
       [-3,  9]])

In [100]:
B@A

array([[-21,  18],
       [ 18, -39]])

In [60]:
print("A[0,:] = ", A[0,:],"\n")
print("B[:,0] = ", B[:,0],"\n")
print("A[0,:]@B[:,0] = ", A[0,:]@B[:,0],"\n")

A[0,:] =  [-3  1] 

B[:,0] =  [ 6 -3] 

A[0,:]@B[:,0] =  -21 



In [61]:
print("A[0,:] = ", A[1,:],"\n")
print("B[:,0] = ", B[:,1],"\n")
print("A[0,:]@B[:,0] = ", A[1,:]@B[:,0],"\n")

A[0,:] =  [1 1] 

B[:,0] =  [-3  9] 

A[0,:]@B[:,0] =  3 



In [76]:
#11
A = np.array([[2,-2,3],[2,3,5],[-4,-4,4]])
x  = np.array([2,2,-3])
A@x

array([ -9,  -5, -28])

In [78]:
#12
A = np.array([[1,-3,2],[1,5,4],[5,1,5]])
x  = np.array([3,3,-3])
A@x

array([-12,   6,   3])