#quiz 11

In [1]:
import numpy as np

#by the independece dimension inequality 
def independenceDimensionInq(k,N):
    if (k <= N): 
        print("\nBy the independence dimension inequality the set of vectors are linerally independent\n")
    else: 
        print("\nBy the independence dimension inequality the set of vectors are linerally dependent\n")
        
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
    #orthogonalization
        q_tilde = a[i]
        print("%s" % i ,q_tilde)
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
            #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

square = np.random.rand(3,3)
print("square matrix columns")
gram_columns = gram_schmidt(square.T)
print(" \n")
print("square matrix rows ")
gram_rows = gram_schmidt(square)
print("\n")

#example of changing one row or column of the square matrix Similiar to VMLS 11.15
print("square matrix row as zero vector ")
square[2,:] = 0
gram_zeroVec = gram_schmidt(square)

#create an m*n matrix 
print("\nWorking with an m*n matrix now\n")
rec = np.random.rand(2,3)

m,n = rec.shape
print("Shape of matrix A: ", m,n)

#first work on the rows 
print("%%%%%%%%%%%%%%%%%% Working on rows first %%%%%%%%%%%%%%%%")
#let N = n from the n-vector which is the length of each n-vector in the set. 
N = n # length of each n-vector 
k = m #let k be the number of n-vectors in the set. 
#check if rows are linerally independent simply by checking if k <= N
independenceDimensionInq(k,N)

print("Using gram schmidt show the same result as the independence dim. ineq. \n")
#Now show they are linerally independent using gram-schmidt 
gram_schmidt(rec)
print("\n%%%%%%%%%%%%% End rows %%%%%%%%%%%%%%%%%%")
#first work on the columns 
print("\n%%%%%%%%%%%% Working on columns next %%%%%%%%%%%%%%")
#let N = n from the n-vector which is the length of each n-vector in the set. 
N = m # length of each n-vector 
k = n #let k be the number of n-vectors in the set. 
#check if rows are linerally independent simply by checking if k <= N
independenceDimensionInq(k,N)
print("Using gram schmidt show the same result as the independence dim. ineq. \n")
#Now show they are linerally independent using gram-schmidt 
g = gram_schmidt(rec.T)

square matrix columns
0 [0.21621699 0.23296603 0.48193898]
1 [0.76286731 0.92987165 0.27044559]
2 [0.03147738 0.41661344 0.10118116]
Vectors are linearly independent.
 

square matrix rows 
0 [0.21621699 0.76286731 0.03147738]
1 [0.23296603 0.92987165 0.41661344]
2 [0.48193898 0.27044559 0.10118116]
Vectors are linearly independent.


square matrix row as zero vector 
0 [0.21621699 0.76286731 0.03147738]
1 [0.23296603 0.92987165 0.41661344]
2 [0. 0. 0.]
Vectors are linearly dependent.
GS algorithm terminates at iteration  3

Working with an m*n matrix now

Shape of matrix A:  2 3
%%%%%%%%%%%%%%%%%% Working on rows first %%%%%%%%%%%%%%%%

By the independence dimension inequality the set of vectors are linerally independent

Using gram schmidt show the same result as the independence dim. ineq. 

0 [0.8047641  0.54529609 0.43153725]
1 [0.70177377 0.76359597 0.05526124]
Vectors are linearly independent.

%%%%%%%%%%%%% End rows %%%%%%%%%%%%%%%%%%

%%%%%%%%%%%% Working on columns next %%%%%

In [16]:
A = np.array([[0,1],[1,-1]])
B = np.array([[1,-1],[0,1]])

In [17]:
A+B

array([[1, 0],
       [1, 0]])

In [18]:
gram_schmidt(A)
gram_schmidt(B)

0 [0 1]
1 [ 1 -1]
Vectors are linearly independent.
0 [ 1 -1]
1 [0 1]
Vectors are linearly independent.


[array([ 0.70710678, -0.70710678]), array([0.70710678, 0.70710678])]

In [19]:
gram_schmidt(A+B)

0 [1 0]
1 [1 0]
Vectors are linearly dependent.
GS algorithm terminates at iteration  2


[array([1., 0.])]

In [29]:
Block = np.block([[A,A+B],[np.zeros([2,2]),B]])
gram_schmidt(Block)

0 [0. 1. 1. 0.]
1 [ 1. -1.  1.  0.]
2 [ 0.  0.  1. -1.]
3 [0. 0. 0. 1.]
Vectors are linearly independent.


[array([0.        , 0.70710678, 0.70710678, 0.        ]),
 array([ 0.57735027, -0.57735027,  0.57735027,  0.        ]),
 array([-0.3086067 , -0.15430335,  0.15430335, -0.9258201 ]),
 array([-0.75592895, -0.37796447,  0.37796447,  0.37796447])]

In [30]:
multiplication = A@B@A
gram_schmidt(multiplication)

0 [ 1 -1]
1 [-2  3]
Vectors are linearly independent.


[array([ 0.70710678, -0.70710678]), array([0.70710678, 0.70710678])]