__Notes__

Where $i$ is an index between 1 and k. 

$A_i = A_{1:n,1:i}$

$Q_i = Q_{1:n,1:i}$

$R_i = R_{1:i,1:i}$

In [2]:
import numpy as np
#This is extra right?
#A= np.random.rand(5,5)
#print("Matrix A: \n", A,"\n \n","shape of A: ", A.shape)

In [3]:
A= np.random.rand(5,5)
print("Matrix A: \n", A,"\n \n","shape of A: ", A.shape)
#compute Q and R
Q, R = np.linalg.qr(A)
print("Q : \n", Q)
print("R : \n", R)

Matrix A: 
 [[0.33034109 0.71580536 0.18801903 0.70170622 0.229004  ]
 [0.51837811 0.48997436 0.9041436  0.81240499 0.24774311]
 [0.67538163 0.8360216  0.74149256 0.73162946 0.55811785]
 [0.85930786 0.34657043 0.8988416  0.4182932  0.40733524]
 [0.38530042 0.99909042 0.83569197 0.53745956 0.40137162]] 
 
 shape of A:  (5, 5)
Q : 
 [[-0.25182066  0.42345047 -0.64483446  0.38047482 -0.44351266]
 [-0.39516222 -0.03714235  0.56092415  0.72651215 -0.00338564]
 [-0.51484678  0.17058578 -0.26848226 -0.06032432  0.79379565]
 [-0.65505467 -0.57747913 -0.07580093 -0.32893176 -0.3513963 ]
 [-0.29371644  0.67581691  0.43786312 -0.46431012 -0.22292189]]
R : 
 [[-1.3118109  -1.32476883 -1.62063238 -1.30627858 -0.82762813]
 [ 0.          0.90258772  0.21823531  0.51343745  0.21900319]
 [ 0.          0.          0.48462289  0.0104104  -0.01367988]
 [ 0.          0.          0.          0.42593077 -0.08689584]
 [ 0.          0.          0.          0.          0.10801597]]


Here we can take a sub set of the columns and run QR factorization on them. The result is the same for the set of columns when compared to the result for QR factorization which is run on the whole matrix A. This seems to only be true when you start with column 1 though.

In [4]:
#compute the submatrix of A using only columns and 
#for some reason starting at index other than 1 results in a different input. 
subA = A[:,0:len(A)-1]
subA

array([[0.33034109, 0.71580536, 0.18801903, 0.70170622],
       [0.51837811, 0.48997436, 0.9041436 , 0.81240499],
       [0.67538163, 0.8360216 , 0.74149256, 0.73162946],
       [0.85930786, 0.34657043, 0.8988416 , 0.4182932 ],
       [0.38530042, 0.99909042, 0.83569197, 0.53745956]])

In [5]:
#compute Q and R
Qsub, Rsub = np.linalg.qr(subA)
Qsub

array([[-0.25182066,  0.42345047, -0.64483446,  0.38047482],
       [-0.39516222, -0.03714235,  0.56092415,  0.72651215],
       [-0.51484678,  0.17058578, -0.26848226, -0.06032432],
       [-0.65505467, -0.57747913, -0.07580093, -0.32893176],
       [-0.29371644,  0.67581691,  0.43786312, -0.46431012]])

In [6]:
Rsub

array([[-1.3118109 , -1.32476883, -1.62063238, -1.30627858],
       [ 0.        ,  0.90258772,  0.21823531,  0.51343745],
       [ 0.        ,  0.        ,  0.48462289,  0.0104104 ],
       [ 0.        ,  0.        ,  0.        ,  0.42593077]])

Now lets say you start at colunm 2 (assuming index starts at 1) and end at n, 
Notice this does not reproduce the same result as the example above as we did not start at column1. We would expect the output of the QR factorization here to be equivalent to the last 4 columns of Q and R, but the set of liner equations used here does not include a1. 

In [79]:
subA = A[:,1:len(A)]
subA

array([[0.48124987, 0.95090771, 0.35587306, 0.63543975],
       [0.58702871, 0.34023289, 0.76234516, 0.69833105],
       [0.14436696, 0.17138524, 0.49384375, 0.47692822],
       [0.99947029, 0.25890063, 0.24405556, 0.69732928],
       [0.9900447 , 0.41091265, 0.81308413, 0.78465062]])

In [80]:
#compute Q and R
Qsub, Rsub = np.linalg.qr(subA)
Qsub

array([[-0.29983541,  0.91785386,  0.25948005,  0.00974069],
       [-0.3657393 ,  0.0435062 , -0.53202403, -0.02973423],
       [-0.08994564,  0.12584928, -0.54983777, -0.67924117],
       [-0.62270475, -0.34652179,  0.52741307, -0.45706725],
       [-0.61683228, -0.14048526, -0.26293425,  0.57336024]])

In [81]:
Rsub

array([[-1.60504683, -0.83965053, -1.08345312, -1.40706015],
       [ 0.        ,  0.76172339,  0.22315918,  0.321772  ],
       [ 0.        ,  0.        , -0.6698475 , -0.30740905],
       [ 0.        ,  0.        ,  0.        , -0.20736291]])

***********************************************************************************

Let's just try rearranging our original matrix A - same vectors, different order.
We will take the first vector and put it at the end.

Notice we do not get the identical oringal matrices Q and R. 

In [82]:
subC = A[:,0:1] #Isolate 1st vector.
subC

array([[0.3355661 ],
       [0.58849913],
       [0.47784412],
       [0.04727853],
       [0.5736844 ]])

In [83]:
Rearrange = np.concatenate((subA, subC),axis=1)
New

array([[0.0026718 , 0.99863298, 0.53632665, 0.47928226, 0.80788459],
       [0.50213999, 0.78627121, 0.1562185 , 0.14693852, 0.32287915],
       [0.67771223, 0.65254325, 0.70697516, 0.61558014, 0.54231922],
       [0.28047323, 0.6682593 , 0.30778936, 0.66471755, 0.5139816 ],
       [0.86236805, 0.87240142, 0.55867313, 0.77934039, 0.44610407]])

In [84]:
#compute Q and R
QRe, RRe = np.linalg.qr(Rearrange)
QRe

array([[-0.29983541,  0.91785386,  0.25948005,  0.00974069,  0.01477291],
       [-0.3657393 ,  0.0435062 , -0.53202403, -0.02973423, -0.76184532],
       [-0.08994564,  0.12584928, -0.54983777, -0.67924117,  0.4608488 ],
       [-0.62270475, -0.34652179,  0.52741307, -0.45706725, -0.07131911],
       [-0.61683228, -0.14048526, -0.26293425,  0.57336024,  0.4493389 ]])

In [85]:
Q

array([[-0.33248496,  0.0816728 ,  0.93914409,  0.02215257,  0.01734779],
       [-0.58309558, -0.09299725, -0.17493844, -0.55239203, -0.56179235],
       [-0.4734566 , -0.38098486, -0.14973981,  0.76511649, -0.15120891],
       [-0.04684442,  0.86800407, -0.09253658,  0.31149597, -0.37253427],
       [-0.56841688,  0.29342894, -0.23752872, -0.10926724,  0.72280183]])

In [86]:
RRe

array([[-1.60504683, -0.83965053, -1.08345312, -1.40706015, -0.74213947],
       [ 0.        ,  0.76172339,  0.22315918,  0.321772  ,  0.2967631 ],
       [ 0.        ,  0.        , -0.6698475 , -0.30740905, -0.61466568],
       [ 0.        ,  0.        ,  0.        , -0.20736291, -0.03148297],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.03123273]])

In [87]:
R

array([[-1.00926701, -1.18023139, -0.84139201, -1.2702595 , -1.32294736],
       [ 0.        ,  1.08776338,  0.32602785,  0.22044578,  0.64077669],
       [ 0.        ,  0.        ,  0.68629503, -0.08881035,  0.15228388],
       [ 0.        ,  0.        ,  0.        , -0.04820302,  0.12470842],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.14604151]])

In [91]:
UndoA = Q @ R
UndoA


array([[0.3355661 , 0.48124987, 0.95090771, 0.35587306, 0.63543975],
       [0.58849913, 0.58702871, 0.34023289, 0.76234516, 0.69833105],
       [0.47784412, 0.14436696, 0.17138524, 0.49384375, 0.47692822],
       [0.04727853, 0.99947029, 0.25890063, 0.24405556, 0.69732928],
       [0.5736844 , 0.9900447 , 0.41091265, 0.81308413, 0.78465062]])

In [89]:
A


array([[0.3355661 , 0.48124987, 0.95090771, 0.35587306, 0.63543975],
       [0.58849913, 0.58702871, 0.34023289, 0.76234516, 0.69833105],
       [0.47784412, 0.14436696, 0.17138524, 0.49384375, 0.47692822],
       [0.04727853, 0.99947029, 0.25890063, 0.24405556, 0.69732928],
       [0.5736844 , 0.9900447 , 0.41091265, 0.81308413, 0.78465062]])

In [90]:
UndoRearrange = QRe @ RRe
UndoRearrange

array([[0.48124987, 0.95090771, 0.35587306, 0.63543975, 0.3355661 ],
       [0.58702871, 0.34023289, 0.76234516, 0.69833105, 0.58849913],
       [0.14436696, 0.17138524, 0.49384375, 0.47692822, 0.47784412],
       [0.99947029, 0.25890063, 0.24405556, 0.69732928, 0.04727853],
       [0.9900447 , 0.41091265, 0.81308413, 0.78465062, 0.5736844 ]])

In [92]:
Rearrange

array([[0.48124987, 0.95090771, 0.35587306, 0.63543975, 0.3355661 ],
       [0.58702871, 0.34023289, 0.76234516, 0.69833105, 0.58849913],
       [0.14436696, 0.17138524, 0.49384375, 0.47692822, 0.47784412],
       [0.99947029, 0.25890063, 0.24405556, 0.69732928, 0.04727853],
       [0.9900447 , 0.41091265, 0.81308413, 0.78465062, 0.5736844 ]])