__Notes__

Where $i$ is an index between 1 and k. 

$A_i = A_{1:n,1:i}$

$Q_i = Q_{1:n,1:i}$

$R_i = R_{1:i,1:i}$

In [1]:
import numpy as np
A= np.random.rand(5,5)
print("Matrix A: \n", A,"\n \n","shape of A: ", A.shape)

Matrix A: 
 [[0.71534334 0.12210969 0.69228255 0.4439404  0.10297887]
 [0.07722592 0.81849298 0.63335186 0.57062569 0.26849716]
 [0.61718097 0.23574274 0.92377441 0.24301442 0.59678871]
 [0.50744837 0.44813905 0.28681143 0.60601874 0.61855472]
 [0.79128184 0.0713826  0.11244008 0.60974292 0.82692488]] 
 
 shape of A:  (5, 5)


In [2]:
A= np.random.rand(5,5)
print("Matrix A: \n", A,"\n \n","shape of A: ", A.shape)
#compute Q and R
Q, R = np.linalg.qr(A)
print("Q : \n", Q)
print("R : \n", R)

Matrix A: 
 [[0.67359815 0.38598051 0.49155552 0.78194709 0.069359  ]
 [0.89895144 0.25959498 0.09571786 0.72271058 0.71619656]
 [0.67328167 0.12721853 0.73997544 0.89039517 0.12769652]
 [0.01011897 0.34985576 0.92776889 0.52661214 0.51627557]
 [0.42208311 0.53283009 0.09607397 0.30244447 0.44166903]] 
 
 shape of A:  (5, 5)
Q : 
 [[-0.48952877  0.18191041 -0.05898815 -0.49354804 -0.69296531]
 [-0.65330137 -0.22805586  0.25800819 -0.30861258  0.59948136]
 [-0.48929877 -0.29464695 -0.56698221  0.58504533 -0.10011507]
 [-0.00735383  0.63670791 -0.62698673 -0.22684186  0.38727169]
 [-0.30674346  0.65014256  0.46408079  0.51713958 -0.02046429]]
R : 
 [[-1.37601341 -0.58680511 -0.70152496 -1.38724815 -0.70360286]
 [ 0.          0.54269861  0.50273811  0.24700385  0.42752348]
 [ 0.          0.         -0.96096557 -0.55431875 -0.01043626]
 [ 0.          0.          0.         -0.05109617 -0.06925939]
 [ 0.          0.          0.          0.          0.55939923]]


Here we can take a sub set of the columns and run QR factorization on them. The result is the same for the set of columns when compared to the result for QR factorization which is run on the whole matrix A. This seems to only be true when you start with column 1 though.

In [3]:
#compute the submatrix of A using only columns and 
#for some reason starting at index other than 1 results in a different input. 
subA = A[:,0:len(A)-1]
subA

array([[0.67359815, 0.38598051, 0.49155552, 0.78194709],
       [0.89895144, 0.25959498, 0.09571786, 0.72271058],
       [0.67328167, 0.12721853, 0.73997544, 0.89039517],
       [0.01011897, 0.34985576, 0.92776889, 0.52661214],
       [0.42208311, 0.53283009, 0.09607397, 0.30244447]])

In [4]:
#compute Q and R
Qsub, Rsub = np.linalg.qr(subA)
Qsub

array([[-0.48952877,  0.18191041, -0.05898815, -0.49354804],
       [-0.65330137, -0.22805586,  0.25800819, -0.30861258],
       [-0.48929877, -0.29464695, -0.56698221,  0.58504533],
       [-0.00735383,  0.63670791, -0.62698673, -0.22684186],
       [-0.30674346,  0.65014256,  0.46408079,  0.51713958]])

In [5]:
Rsub

array([[-1.37601341, -0.58680511, -0.70152496, -1.38724815],
       [ 0.        ,  0.54269861,  0.50273811,  0.24700385],
       [ 0.        ,  0.        , -0.96096557, -0.55431875],
       [ 0.        ,  0.        ,  0.        , -0.05109617]])

Now lets say you start at colunm 2 (assuming index starts at 1) and end at n, 
Notice this does not reproduce the same result as the example above as we did not start at column1. We would expect the output of the QR factorization here to be equivalent to the last 4 columns of Q and R, but the set of liner equations used here does not include a1. 

In [6]:
subA = A[:,1:len(A)]
subA

array([[0.38598051, 0.49155552, 0.78194709, 0.069359  ],
       [0.25959498, 0.09571786, 0.72271058, 0.71619656],
       [0.12721853, 0.73997544, 0.89039517, 0.12769652],
       [0.34985576, 0.92776889, 0.52661214, 0.51627557],
       [0.53283009, 0.09607397, 0.30244447, 0.44166903]])

In [7]:
#compute Q and R
Qsub, Rsub = np.linalg.qr(subA)
Qsub

array([[-0.48290515,  0.08067368, -0.22676309,  0.64072081],
       [-0.3247826 , -0.18865807, -0.65678251, -0.62293584],
       [-0.15916473,  0.62431648, -0.43804708,  0.16255502],
       [-0.43770902,  0.57183491,  0.5110572 , -0.41222813],
       [-0.66663054, -0.49105362,  0.25327956,  0.07121528]])