In [6]:
#6.3 Joaquin Quintana

![title]("IMG-0068.png")

__a.__ True - K is always sqaure. Think about this from the point of view of $A$ and $A^T$ which makes up two sections of the block matrix and have shapes $m*n$ and $n*m$. Then to make up the last part of the block we must have the sizes which are missing which are m*m and $n*n$ in size. These missing sizes nicely match the size of the Identity matrix and the zero matrix. This can be seen in the picture below. Additionally, the identity matrix always has shape $n*n$.

__b.__ True - from the image we see that A has all the same length sides which are of size n+m. This implies A is a square. 

__c.__ True - when the matrix is transposed the Identity matrix and zero matrix end up in the same location. Additionally, when we transpose $A^T$ we get back $A$ which ends up in the place where matrix $A$ was before being transposed and vice versa. This is easy to demonstate in python

In [22]:
import numpy as np
#create a block vector which matches the problem parameters
def blockMatrix(col,row):
    I = np.identity(row) #identity matrix of size m * m
    A = np.random.randint(15, size=(col, row)) #create a matrix A of size m * n. Place random ints between 0 and 15 
    Z = np.zeros([col,col]) # zero matrix of size n * n
    block = np.block([[I,A.T],[A,Z]]) #create our block matrix
    return block

Block = blockMatrix(15,120)
Transposed_Block = Block.T
#check that transposed matrix is equivalent. This is K == K^T
print(Block,"\n")
print("Is the transposed block and orginal block matrix equivalent : ",np.allclose(Block,Transposed_Block))

[[ 1.  0.  0. ...  3. 11.  5.]
 [ 0.  1.  0. ... 10. 14.  3.]
 [ 0.  0.  1. ... 10.  5.  0.]
 ...
 [ 3. 10. 10. ...  0.  0.  0.]
 [11. 14.  5. ...  0.  0.  0.]
 [ 5.  3.  0. ...  0.  0.  0.]] 

Is the transposed block and orginal block matrix equivalent :  True


__d.__ False - They only have the same dimensions when $A$ is sqaure or when $m = n$ (number of rows equal the number of columns). All other times the identity matrix has size $n*n$ and the zero matrix has size $m*m$. The image below helps show this.   

__e.__ True - This is covered in d but the zero matrix is in the right corner and neighboring $A$ and $A^T$ which makes both of its sides of size m. Therefore this zero matrix is square.   

# 3. 6.9

This problem looks at the 3 vectors which are related to the reach matrix R. 

a. Here we see n-vector c gives the total amount of money that the company put forth for all channels with each $c_i$ being the amount shelled out for the $i^{th}$ channel. To get the total amount invested for all n-channels we need to simply sum the vector. This is $totalInvestment = 1^Tc$ 

b. We can see that these vectors are related and that the problem is setup to have the reach matrix return the ratio for the number of views in segment i for each dollar spent on channel j. This translates to $R_{i,j} = \frac{v_i}{c_j}$ and gives us a nice ratio to determine how well this channel is doing in comparison to the money put in. So by way of simple algebraic manipulation we can say $v = Rc$. 

c. Much like part b we are going to look at the vectors and how they relate to each other with regards to dimensional analysis. To find the total sales we will look at vectors v and a. Each $v_i$ is the number of impressions for segment i and $a_i$ is a ratio which gives the profit per impression in segment i.   

By multiplying $v_i$ by $c_i$ we get the total profit for group i. For example...

Let $ v_i = 2*imp$ __and__ $a_i = \frac{50.00 usd}{1}*imp $

__then__ $v_ia_i = \frac{2*imp}{1}* \frac {50.00 usd}{imp} = 100 usd$

And to get the total profit for all groups we can simply do this elementwise for the two vectors. This is compute the inner product of v and a or $v^Ta$. Finally, from part b we see that by simple subtitution we get $Rc^Ta = a^TRc$

d. We are told $R_{i,j}$ gives the ratio of views in segment $i$ for dollars spent on channel $j$. So from this we need to look at $R_{3,j}$ or row 3 of the reach matrix $R$. We see that this ratio will be larger when views are high and dollars spent is low and low when views are low and dollars spent is high. Therefore this implies we are searching for the maximum element in Row 3 of the reach matrix $R$. 

e. This is somewhat explained in part d and I'll elaborate from there. If $R_{3,5}$ is smaller than all other elements in $R$ we know there are low views in comparison to the amount of money put in incomparison to all other $R_{i,j} \neq R_{3,5}$. This is, all other $R_{i,j}$ are larger which implies they all have more views than dollars put in in comparison to $R_{i,j}$.

# 5 6.17

a. This problem is similar to 5.1 a but with matricies. This is, we know the identity matrix is linerally independent and can say that $\alpha I = 0$ and therefore $\alpha = 0$. Since these matricies are stacked we can represent them as follows ...  

$S = \alpha\begin{bmatrix} A  \\ I \end{bmatrix}= \begin{bmatrix}  \alpha A  \\  \alpha I \end{bmatrix} = 0$

and since $Sx = 0$ we can say $S$ is linerally independent with coefficent $x = 0$. 

b. Linear independence inequality says that if an n-vector x is composed of $a_1,...,a_k$ vecotrs and has $k \leq n$ then x is a set of linearly independent vectors. If k = n+1 then we can say they are linearly dependent. We see there are m+n rows in $S$ and each row is of size n. Lets translate this a bit and let m+n equal k and we see that we have k>n or that that rows are linerally dependent. 

Below I confirm this result for S the Gram-Schmidt algorithm. 

In [33]:
import numpy as np
#function provided in python companion notebook
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
    #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
            #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

#define A, I and S which is the stacked vector
I = np.identity(5) #identity matrix of size n * n
A = np.random.randint(9, size=(4, 5)) #create a matrix A of size m * n. Place random ints between 0 and 9 
S = np.concatenate([A,I],axis=0)
ST = S.T
n,m = S.shape

print("Stacked matrix S = (A,I): ","\n",S,"\n",)

#print rows 
print("rows of S")
[print("row " + str(row)+ ": " , S[row]) for row in range(n)]
print("\n")

#print columns 
print("columns of S")
[print("column "+ str(col)+ ": " ,ST[col]) for col in range(m)]   
print("\n")

#Show the rows are lineraly dependent
print("Running Gram-schmidt on rows of S")
gram_schmidt(S)
print("\n")

#Show the columns are lineraly independent
print("Running Gram-schmidt on columns of S")
gram_schmidt(S.T)

Stacked matrix S = (A,I):  
 [[4. 5. 7. 5. 5.]
 [3. 7. 7. 0. 3.]
 [0. 0. 0. 3. 8.]
 [5. 0. 0. 4. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

rows of S
row 0:  [4. 5. 7. 5. 5.]
row 1:  [3. 7. 7. 0. 3.]
row 2:  [0. 0. 0. 3. 8.]
row 3:  [5. 0. 0. 4. 0.]
row 4:  [1. 0. 0. 0. 0.]
row 5:  [0. 1. 0. 0. 0.]
row 6:  [0. 0. 1. 0. 0.]
row 7:  [0. 0. 0. 1. 0.]
row 8:  [0. 0. 0. 0. 1.]


columns of S
column 0:  [4. 3. 0. 5. 1. 0. 0. 0. 0.]
column 1:  [5. 7. 0. 0. 0. 1. 0. 0. 0.]
column 2:  [7. 7. 0. 0. 0. 0. 1. 0. 0.]
column 3:  [5. 0. 3. 4. 0. 0. 0. 1. 0.]
column 4:  [5. 3. 8. 0. 0. 0. 0. 0. 1.]


Running Gram-schmidt on rows of S
Vectors are linearly dependent.
GS algorithm terminates at iteration  6


Running Gram-schmidt on columns of S
Vectors are linearly independent.


[array([0.56011203, 0.42008403, 0.        , 0.70014004, 0.14002801,
        0.        , 0.        , 0.        , 0.        ]),
 array([ 0.27519714,  0.70764978,  0.        , -0.6199496 , -0.12398992,
         0.15423136,  0.        ,  0.        ,  0.        ]),
 array([ 0.58988218, -0.35057597,  0.        , -0.25150016, -0.05030003,
        -0.49537909,  0.46685397,  0.        ,  0.        ]),
 array([ 0.26668575, -0.23280191,  0.78427138, -0.03061505, -0.21526204,
         0.29618463, -0.23718688,  0.26142379,  0.        ]),
 array([-0.27567605,  0.2509569 ,  0.5933028 ,  0.00340607,  0.33280316,
        -0.37831802,  0.17303408, -0.41515244,  0.22984501])]

# 6-6.22

__Info Needed__ 
* Additon and multiplication of two $m*n$ matricies each requires $mn$ flops
* Adding vectors takes $n$ flops 
* Matrix-vector mulitplication takes $2nm$ flops

We are given $z = (A+B)(x+y)$ where $A$ and $B$ are matricies and $x$ and $y$ are n-vectors

a) compute $z$ as presented above. We see that matrix addtion $A+B$ and $x+y$ costs $mn$ and $n$ flops respecitively. Then we need to multiply their results which is between a matrix and a n-vector which cost 2nm flops. So we have $3nm +n$ flops but we drop the $n$ as $3nm$ is the leading term. So this operation costs $3nm$ flops. 

b) Cost if z's contents were distributed to be $z = Ax + Ay +Bx + By$. Here we see there are four matrix-vector multiplications which costs $2nm$ each for a total cost of $8nm$.

c) We see that the by distributing we made the computatinal complexity greater aka worse. Therefore, we would want to use the first method as it requires fewer flops to perform the an equivalent computation.  

# 6.6.13

Given a polynomial of degree n-1, $p(t) = c_1 +c_2t +...+ c_nt^{n-1}$, and its derivative of degree n-2,  $p'(t) = d_1 + d_2t + ... + d_{n-1}t^{n-2}$, find a matrix $D$ for which the matrix times the polynmoial results in the derivative of the polynomial, i.e., $d = Dc$. We can achieve this goal by letting D be a matrix with the first column being all zeros and of size $(n-1*1)$ and the rest of the columns of D can be represented by $diag(1,2,...,n-1)$. By doing this we get $d = Dc$ = ...

$d_0 = c_1 * 0 = 0$ 

$d_1 = c_2 * 1 = c_2$

$d_2 = c_3 * 2 = 3c_3$

$d_3 = c_4 * 2 = 3c_4$

...

$d_n-1 = c_n * (n-1) = (n-1)c_n$

which achieve the goal at hand.