In [3]:
import numpy as np

In [4]:
#create matrix
a = np.array([[9,7,2],[9,3,4],[3,9,9]])
b = np.array([[4,5,3],[4,7,4],[2,2,9]])

In [31]:
print(b)

[[4 5 3]
 [4 7 4]
 [2 2 9]]


In [30]:
#ith row of a
print(a[0,:])
#jth column of b
print(b[:,0])
#inner product of the ith row of a and the jth column of b
a[0,:]@ b[:,0]

[9 7 2]
[4 4 2]


68

In [29]:
#compute the product of matricies a and b 
ab = np.zeros([3,3])
for i in range(3):
    for j in range(3):
#inner product of the ith row of a and the jth column of b
        ab[i][j] = a[i,:]@ b[:,j]
print(ab)

[[ 68.  98.  73.]
 [ 56.  74.  75.]
 [ 66.  96. 126.]]


In [34]:
#create matrix
c = np.array([[0,2,-1],[-2,1,1]])
d = np.array([2,1,-1])

c@d

array([ 3, -4])

In [36]:
# 3 

In [40]:
#create matrix
A = np.array([[2,5,2],[5,4,1],[1,4,1]])
B = np.array([[5,1,1],[3,1,5],[5,2,4]])

#compute the product of matricies a and b 
AB = np.zeros([3,3])
for i in range(3):
    for j in range(3):
#inner product of the ith row of a and the jth column of b
        AB[i][j] = A[i,:]@ B[:,j]
print(AB)


[[35. 11. 35.]
 [42. 11. 29.]
 [22.  7. 25.]]


In [41]:
#create matrix
A = np.array([[2,5,2],[5,4,1],[1,4,1]])
B = np.array([[5,1,1],[3,1,5],[5,2,4]])

#compute the product of matricies a and b 
BA = np.zeros([3,3])
for i in range(3):
    for j in range(3):
#inner product of the ith row of a and the jth column of b
        BA[i][j] = B[i,:]@ A[:,j]
print(BA)

[[16. 33. 12.]
 [16. 39. 12.]
 [24. 49. 16.]]


In [48]:
#create matrix
A = np.array([[3,2,1],[1,1,1],[1,1,3]])
B = np.array([[4,2,5],[4,5,1],[2,2,3]])

#compute the product of matricies a and b 
AB = np.zeros([3,3])
for i in range(3):
    for j in range(3):
#inner product of the ith row of a and the jth column of b
        AB[i][j] = A[i,:]@ B[:,j]
print("AB: \n",AB,"\n")   
#compute the product of matricies b and a 
BA = np.zeros([3,3])
for i in range(3):
    for j in range(3):
#inner product of the ith row of a and the jth column of b
        BA[i][j] = B[i,:]@ A[:,j]
print("BA: \n",BA,"\n")

print("AB - BA: \n",AB - BA)

AB: 
 [[22. 18. 20.]
 [10.  9.  9.]
 [14. 13. 15.]] 

BA: 
 [[19. 15. 21.]
 [18. 14. 12.]
 [11.  9. 13.]] 

AB - BA: 
 [[ 3.  3. -1.]
 [-8. -5. -3.]
 [ 3.  4.  2.]]


In [49]:
# 5 

In [58]:
#create matrix
A = np.array([1,2,3,4])
B = np.array([6,8,7,4])


array([1, 2, 3, 4])

In [54]:
# 9 
A = np.array([[0,2,1,8],[4,1,0,5],[6,7,0,4],[3,6,1,4]])
A.T

array([[0, 4, 6, 3],
       [2, 1, 7, 6],
       [1, 0, 0, 1],
       [8, 5, 4, 4]])

In [59]:
#6 

In [64]:
#create matrix
A = np.array([[3,1],[2,1]])
B = np.array([[-3,3],[6,3]])
A@B

array([[-3, 12],
       [ 0,  9]])

In [69]:
#create matrix
A = np.array([[2,-3,4],[4,1,3],[-5,-4,5]])
B = np.array([1,2,-3])
bt = B.T
A@bt

array([-16,  -3, -28])

In [70]:
#8
#create matrix
A = np.array([[0,-3,4],[2,1,3],[1,1,2]])
B = np.array([3,2,-3])
bt = B.T
A@bt

array([-18,  -1,  -1])