In [1]:
# 8.4a
import numpy as np

def flipImage(x):
    #get img dimension and reshape img into a n-vector
    siz = x.shape
    x = x.flatten('F')
    #create matrix A which is shown in latex below
    I = np.identity(3)
    rm = np.fliplr(I) #reverserMatrix
    z = np.zeros([3,3])
    A = np.block([[rm,z,z],[z,rm,z],[z,z,rm]]) 
    print("Matrix A: \n",A)
    #compute y= Ax
    y = A@x 
    print(y)
    #why do must I reverse the list here? To get it back into the correct shape
    #y= y[::-1]
    #print(y)
    return np.reshape(y, siz, order='F') 

In [2]:
x = np.array([[1,4,7],[2,5,8],[3,6,9]])
x

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [3]:
flipImage(x)

Matrix A: 
 [[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[3. 2. 1. 6. 5. 4. 9. 8. 7.]


array([[3., 6., 9.],
       [2., 5., 8.],
       [1., 4., 7.]])